import {
  AppWindow,
  Gauge,
  ServerCog,
  Database,
  ClipboardList,
  Handshake,
} from 'lucide-react';

export const SKILL_CATEGORIES = [
  {
    id: 'realiser',
    icon: <AppWindow size={28} />,
    title: 'Réaliser',
    subtitle: 'Développement',
    description: 'Conception et réalisation d\'applications web et mobiles',
    tagline: 'BUILD & CREATE',
    languages: ['Python', 'PHP', 'JavaScript', 'Java', 'Kotlin' , 'C'],
    frameworks: ['React', 'Java Spring', 'Vue.js', 'Flutter', 'Laravel'],
    libraries: ['scikit-learn', 'PyTorch'],
    tools: ['VS Code', 'Jetbrain', 'Android Studio', 'Postman', 'Figma'],
    color: '#8f7aff',
    gradient: 'linear-gradient(135deg, #8f7aff 0%, #6366f1 100%)',
  },
  {
    id: 'optimiser',
    icon: <Gauge size={28} />,
    title: 'Optimiser',
    subtitle: 'Performance',
    description: 'Conception d\'applications optimisees selon les contraintes de temps, precision et consommation de ressources. Analyse algorithmique, choix de structures de donnees adaptees et evaluation de l\'impact environnemental des solutions.',
    tagline: 'PERFORMANCE',
    languages: ['Java', 'Python'],
    frameworks: [],
    architectures: ['MVC', 'MVVM', 'Clean Architecture', 'Design Patterns'],
    tests: ['JUnit 5', 'PyTest', 'Flutter Test'],
    tools: [],
    color: '#ffd93d',
    gradient: 'linear-gradient(135deg, #ffd93d 0%, #f59e0b 100%)',
  },
  {
    id: 'administrer',
    icon: <ServerCog size={28} />,
    title: 'Administrer',
    subtitle: 'Infrastructure',
    description: 'Gestion et administration de systèmes et réseaux',
    tagline: 'INFRASTRUCTURE',
    languages: ['Bash', 'PowerShell'],
    frameworks: [],
    tools: ['Linux', 'Windows Server', 'VirtualBox', 'VMware', 'Proxmox', 'Docker', 'Kubernetes', 'Minikube'],
    color: '#00d4ff',
    gradient: 'linear-gradient(135deg, #00d4ff 0%, #0ea5e9 100%)',
  },
  {
    id: 'gerer',
    icon: <Database size={28} />,
    title: 'Gérer',
    subtitle: 'Données',
    description: 'Gestion de bases de données et administration de données',
    tagline: 'DATA MANAGEMENT',
    languages: ['Python', 'SQL'],
    frameworks: [],
    tools: ['MySQL', 'PostgreSQL', 'MongoDB', 'Redis', 'phpMyAdmin', 'DBeaver'],
    color: '#ff6b6b',
    gradient: 'linear-gradient(135deg, #ff6b6b 0%, #f43f5e 100%)',
  },
  {
    id: 'conduire',
    icon: <ClipboardList size={28} />,
    title: 'Conduire',
    subtitle: 'Gestion de projet',
    description: 'Planification, organisation et suivi de projets',
    tagline: 'PROJECT LEADING',
    languages: [],
    frameworks: [],
    tools: ['GitLab', 'Trello', 'Notion', 'ClickUp', 'GitHub Projects'],
    color: '#a855f7',
    gradient: 'linear-gradient(135deg, #a855f7 0%, #7c3aed 100%)',
  },
  {
    id: 'collaborer',
    icon: <Handshake size={28} />,
    title: 'Collaborer',
    subtitle: 'Travail d\'équipe',
    description: 'Communication et collaboration en équipe',
    tagline: 'TEAMWORK',
    languages: [],
    methods: ['Agile', 'Scrum', 'Kanban'],
    tools: ['Git', 'GitHub', 'GitLab', 'Notion', 'Discord', 'Teams', 'Markdown'],
    color: '#ec4899',
    gradient: 'linear-gradient(135deg, #ec4899 0%, #db2777 100%)',
  },
];

export const getTransform3D = (mousePosition: { x: number; y: number }): string => {
  const rotateX = (mousePosition.y - 0.5) * -10;
  const rotateY = (mousePosition.x - 0.5) * 10;
  return `perspective(1000px) rotateX(${rotateX}deg) rotateY(${rotateY}deg)`;
};
